repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: name-tests-test
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.2.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    args: [--py37-plus, --add-import, from __future__ import annotations]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.3.0
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.7.0
  hooks:
  - id: autopep8
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
  - id: mypy
    additional_dependencies: [types-all]
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.1
  hooks:
  - id: poetry-check
  - id: poetry-lock
#  - id: poetry-export
#    verbose: true
#    args: [-f, requirements.txt, -o, requirements.txt]
- repo: https://github.com/iterative/dvc
  rev: main
  hooks:
  - id: dvc-pre-commit
    language_version: python3
    stages:
    - commit
  - id: dvc-pre-push
    language_version: python3
    stages:
    - push
  - id: dvc-post-checkout
    language_version: python3
    stages:
    - post-checkout
    always_run: true
